import {
  Avatar,
  List,
  ListItemAvatar,
  ListItemButton,
  ListItemText,
  ListSubheader,
  Typography,
} from '@mui/material';
import React, { FC } from 'react';
const messages = [
  {
    id: 1,
    primary: 'Brunch this week?',
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: '/static/images/avatar/5.jpg',
  },
  {
    id: 2,
    primary: 'Birthday Gift',
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: '/static/images/avatar/1.jpg',
  },
  {
    id: 3,
    primary: 'Recipe to try',
    secondary:
      'I am try out this new BBQ recipe, I think this might be amazing',
    person: '/static/images/avatar/2.jpg',
  },
  {
    id: 4,
    primary: 'Yes!',
    secondary: 'I have the tickets to the ReactConf for this year.',
    person: '/static/images/avatar/3.jpg',
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      'My appointment for the doctor was rescheduled for next Saturday.',
    person: '/static/images/avatar/4.jpg',
  },
  {
    id: 6,
    primary: 'Discussion',
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: '/static/images/avatar/5.jpg',
  },
  {
    id: 7,
    primary: 'Summer BBQ',
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: '/static/images/avatar/1.jpg',
  },
  {
    id: 8,
    primary: 'Summer BBQ',
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: '/static/images/avatar/1.jpg',
  },
  {
    id: 9,
    primary: 'Summer BBQ',
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: '/static/images/avatar/1.jpg',
  },
];
export const MessageList: FC = () => {
  return (
    <List
      sx={{
        mb: 2,
        height: '65vh',
        overflow: 'auto',
      }}
    >
      {messages.map(({ id, primary, secondary, person }) => (
        <React.Fragment key={id}>
          <ListItemButton>
            {id % 2 === 0 && (
              <>
                <ListItemAvatar>
                  <Avatar alt="Profile Picture" src={person} />
                </ListItemAvatar>
                <ListItemText
                  // primary={primary}
                  secondary={secondary}
                  sx={{
                    maxWidth: '40%',
                    border: '1px solid #f0f0f0',
                    borderRadius: 4,
                    padding: 2,
                    marginRight: 'auto',
                    boxShadow: '14px 18px 21px -10px rgba(0,0,0,0.25)',
                    WebkitBoxShadow: '14px 18px 21px -10px rgba(0,0,0,0.25)',
                  }}
                />
              </>
            )}

            {id % 2 === 1 && (
              <>
                <ListItemText
                  // primary={primary}
                  secondary={<Typography>{secondary}</Typography>}
                  sx={{
                    color: 'white',
                    maxWidth: '40%',
                    border: '1px solid #f0f0f0',
                    borderRadius: 4,
                    padding: 2,
                    marginRight: 2,
                    marginLeft: 'auto',
                    backgroundColor: (theme) => theme.palette.primary.main,
                    boxShadow: '14px 18px 21px -10px rgba(0,0,0,0.25)',
                  }}
                />
                <ListItemAvatar>
                  <Avatar alt="Profile Picture" src={person} />
                </ListItemAvatar>
              </>
            )}
          </ListItemButton>
        </React.Fragment>
      ))}
    </List>
  );
};
